### ISSUE TITLE
next milestone checklist

### ISSUE THREAD

**Issue by realchrisward** [realchrisward/Physiology-Analysis-Tools#18]
- [ ] clean up gui (remove unused controls)
- [ ] add control for selecting settings
- [ ] streamline report
- [ ] permit loading of report
- [ ] beat selection by clicking in graph
- [ ] display arrhyth info
- [ ] either populate text window or remove it
